### ISSUE TITLE
[BUG] Link to dashboard asset is wrong

### ISSUE THREAD

**Issue by Sigri44** [mfrederic/realt-properties-map#8]
**Describe the bug**
Any asset openned, via dashboard, has an error.

**To Reproduce**
1. Go to a property
2. Click on 'Dashboard' button
3. See error

**Screenshots**
<img width="1386" alt="image" src="https://github.com/mfrederic/realt-properties-map/assets/9304947/2a29621a-6084-4056-ba2d-8359a3501f67">

**Comment by mfrederic** [comment]
@Sigri44 After some quick checking, it looks like the issue occurs with only some properties.

It looks like the token addresses of the properties are case-sensitive on the RealT Dashboard. On top of it, it seems the case is inconsistent, as we can see below:

For example, 0x591882dC0581A69f377dF4CaD2CeE4E9855ef34D mixes lower and uppercase.

Internally to RPM, because of the multiple sources of data and since the addresses are case-insensitive, the token addresses are lowercased. It seems it is not the case with the dashboard. This needs to be investigated to see if we can fix it easily, maybe by storing the unaltered token on top of the lowercased one.

**Comment by Sigri44** [comment]
> @Sigri44 After some quick checking, it looks like the issue occurs with only some properties.
> 
> It looks like the token addresses of the properties are case-sensitive on the RealT Dashboard. On top of it, it seems the case is inconsistent, as we can see below:
> 
> For example, 0x591882dC0581A69f377dF4CaD2CeE4E9855ef34D mixes lower and uppercase.
> 
> Internally to RPM, because of the multiple sources of data and since the addresses are case-insensitive, the token addresses are lowercased. It seems it is not the case with the dashboard. This needs to be investigated to see if we can fix it easily, maybe by storing the unaltered token on top of the lowercased one.

You absolutely must ‘checksum’ the addresses (this is a Web3 standard, available in libraries such as ethers.js
